### ISSUE TITLE
同协主无法正常使用

### ISSUE THREAD

**Issue by litoobie** [LoveFurina/KainSR#10]
同协主，不论男女都设置好了仪器，但是游戏里面一堆女同谐主无男同谐主，然后编队替换有配置的女同协主，结果再一看就是啥也没有的同谐主，请问这种情况该怎么办，毕竟想试灵砂流萤

**Comment by litoobie** [comment]
女同谐主的配置内容全删，变成男主了，但是还是一堆男主，队伍配置选有装备的退出重看还是无装备，而且也进不去战斗。看配置文件没发现哪有问题。。。。。。

**Comment by LoveFurina** [comment]
先用/id 8006再试试女同谐主呢
