### ISSUE TITLE
'nest' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by Roloyer** [LoveFurina/KainSR#2]
佬，运行之后cmd显示  'nest' 不是内部或外部命令，也不是可运行的程序或批处理文件。 怎么解决，自己弄了几个小时没用😭😭

**Comment by Roloyer** [comment]
执行完npm install -g @nestjs/cli，会变成有2000多报错（

**Comment by LoveFurina** [comment]
运行过`npm install `了吗

**Comment by Roloyer** [comment]
> 运行过了吗`npm install `
运行了npm install -g @nestjs/cli，经过一番倒腾，现在还是有下面的问题＞﹏＜
![})}D)T{RPGZTWRCB3R}_(4Y](https://github.com/user-attachments/assets/508f1e40-da22-4e48-b51c-0b812b033a8d)
![MNQZDFL5( K60FI~Z_KT@W6](https://github.com/user-attachments/assets/45141f17-8f6f-4306-909d-8e0c79ad007b)

**Comment by Chenyu550** [comment]
> > 运行过了吗`npm install `
> > 运行了npm install -g @nestjs/cli，经过一番倒腾，现在还是有下面的问题＞﹏＜
> > ![})}D)T{RPGZTWRCB3R}_(4Y](https://private-user-images.githubusercontent.com/177384451/354821531-508f1e40-da22-4e48-b51c-0b812b033a8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTY2ODksIm5iZiI6MTcyMjY5NjM4OSwicGF0aCI6Ii8xNzczODQ0NTEvMzU0ODIxNTMxLTUwOGYxZTQwLWRhMjItNGU0OC1iNTFjLTBiODEyYjAzM2E4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDQ2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTc3NzE3NTQ0MzFhM2NkMDQwOWYyYTE3MzYyOGYxOGI5ODJkNjQwOWU0OTY5MzFlOGNlMWFkZWM0Y2U5OTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IY7eGWYHj6Q9bFarb3xP4RhNd6J9H11_4BExiI9jBZk)
> > ![MNQZDFL5( K60FI~Z_KT@W6](https://private-user-images.githubusercontent.com/177384451/354821537-45141f17-8f6f-4306-909d-8e0c79ad007b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTY2ODksIm5iZiI6MTcyMjY5NjM4OSwicGF0aCI6Ii8xNzczODQ0NTEvMzU0ODIxNTM3LTQ1MTQxZjE3LThmNmYtNDMwNi05MDlkLThlMGM3OWFkMDA3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDQ2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWVlYTYzMjRlYjBmNzZjMGRmNjI2N2JlMGJmMzk1MmRlNmFjOTc1NTM2NWE2MjM1NDhhMmYzMjE2MWU5M2RkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MbsI67aoX6gE4O24JL2cN-deW8gYSeQo7beJ-sML4rY)

我看说明上是直接install 后面不带东西的

**Comment by Roloyer** [comment]
> > > 运行过了吗`npm install `
> > > 运行了npm install -g @nestjs/cli，经过一番倒腾，现在还是有下面的问题＞﹏＜
> > > ![})}D)T{RPGZTWRCB3R}_(4Y](https://private-user-images.githubusercontent.com/177384451/354821531-508f1e40-da22-4e48-b51c-0b812b033a8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTY2ODksIm5iZiI6MTcyMjY5NjM4OSwicGF0aCI6Ii8xNzczODQ0NTEvMzU0ODIxNTMxLTUwOGYxZTQwLWRhMjItNGU0OC1iNTFjLTBiODEyYjAzM2E4ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDQ2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOTc3NzE3NTQ0MzFhM2NkMDQwOWYyYTE3MzYyOGYxOGI5ODJkNjQwOWU0OTY5MzFlOGNlMWFkZWM0Y2U5OTdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IY7eGWYHj6Q9bFarb3xP4RhNd6J9H11_4BExiI9jBZk)
> > > ![MNQZDFL5( K60FI~Z_KT@W6](https://private-user-images.githubusercontent.com/177384451/354821537-45141f17-8f6f-4306-909d-8e0c79ad007b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTY2ODksIm5iZiI6MTcyMjY5NjM4OSwicGF0aCI6Ii8xNzczODQ0NTEvMzU0ODIxNTM3LTQ1MTQxZjE3LThmNmYtNDMwNi05MDlkLThlMGM3OWFkMDA3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QxNDQ2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWVlYTYzMjRlYjBmNzZjMGRmNjI2N2JlMGJmMzk1MmRlNmFjOTc1NTM2NWE2MjM1NDhhMmYzMjE2MWU5M2RkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MbsI67aoX6gE4O24JL2cN-deW8gYSeQo7beJ-sML4rY)
> 
> 我看说明上是直接install 后面不带东西的

刚试了，直接运行npm install ，会报错 :'nest' 不是内部或外部命令，也不是可运行的程序
或批处理文件。<(＿　＿)> 一开始就是这个问题

**Comment by LoveFurina** [comment]
你是运行的install.bat还是npm install？

**Comment by Roloyer** [comment]
> 你是运行的install.bat还是npm install？

在cmd里面运行的npm install

**Comment by LoveFurina** [comment]
> > 你是运行的install.bat还是npm install？
> 
> 在cmd里面运行的npm install

在项目根目录运行的吗

**Comment by Roloyer** [comment]
> > > 你是运行的install.bat还是npm install？
> > 
> > 
> > 在cmd里面运行的npm install
> 
> 在项目根目录运行的吗

额是搜索栏直接打开cmd运行的

**Comment by Roloyer** [comment]
> > > 你是运行的install.bat还是npm install？
> > 
> > 
> > 在cmd里面运行的npm install
> 
> 在项目根目录运行的吗

额是左下搜索栏直接打开cmd运行的

**Comment by LoveFurina** [comment]
> > > > 你是运行的install.bat还是npm install？
> > > 
> > > 
> > > 在cmd里面运行的npm install
> > 
> > 
> > 在项目根目录运行的吗
> 
> 额是左下搜索栏直接打开cmd运行的

你试试直接运行install.bat呢

**Comment by Roloyer** [comment]
> > > > > 你是运行的install.bat还是npm install？
> > > > 
> > > > 
> > > > 在cmd里面运行的npm install
> > > 
> > > 
> > > 在项目根目录运行的吗
> > 
> > 
> > 额是左下搜索栏直接打开cmd运行的
> 
> 你试试直接运行install.bat呢
不行，运行完install.bat会直接报错，运行完安装的东西怎么删啊，佬，感觉前前后后装了不少东西
![}E8{6PEK)P{Q}N}BWMK ONR](https://github.com/user-attachments/assets/7d76c5e0-3e03-4665-addc-4be43e4e03ce)

**Comment by LoveFurina** [comment]
换镜像站，看起来是连不上服务器

**Comment by Roloyer** [comment]
> 换镜像站，看起来是连不上服务器
好吧，陌生的领域

**Comment by Roloyer** [comment]
> 换镜像站，看起来是连不上服务器

啊好了好了，莫名其妙可以了。看来连上服务器了，感谢芙佬，一问一答的真是麻烦啦ヾ(^▽^*)))
