### ISSUE TITLE
能否麻烦分享一下v4 v5的更新包

### ISSUE THREAD

**Issue by yu666503** [LoveFurina/KainSR#9]
rt，想试试新版呼雷😳

**Comment by LoveFurina** [comment]
都公开了，自己找啊

**Comment by LoveFurina** [comment]
https://drive.google.com/drive/u/0/folders/14EXPZ45ZbHuo72R97TqgUGp653JeZUE6

**Comment by yu666503** [comment]
> 都公开了，自己找啊

确实是不知道在哪公开的，是有电报群吗

**Comment by 365542449** [comment]
> 都公开了，自己找啊

大佬，要怎么修改怪物的血量啊
